services:
  # TCP-echo server (default SUT)
  tcp-echo:
    image: istio/tcp-echo-server:1.1
    container_name: SUT
    networks:
      - fuzzer_network
    ports:
      - "9000:9000"

  # TCP-mapper
  mapper:
    build:
      context: ./mapper
      dockerfile: Dockerfile
    container_name: tcp-mapper
    privileged: true
    ports:
      - "18200:18200"
    depends_on:
      - tcp-echo
    networks:
      - fuzzer_network
    volumes:
      - ./config:/config

  # TCP-Learner
  learner:
    build:
      context: ./learner
      dockerfile: Dockerfile
    container_name: tcp-learner
    networks:
      - fuzzer_network
    depends_on:
      - tcp-echo
      - mapper
    volumes:
      - ./output:/app/output_folder
      - ./config:/config
    command: "/config/learner_args"

networks:
  fuzzer_network:
    driver: bridge
